services:
  - type: web
    name: stock-trading-web
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
